### ISSUE TITLE
Request: Json that defines current formats

### ISSUE THREAD

**Issue by acron0** [Sembiance/mtgjson#24]
Hiya,

It'd be great if there was a way to cross-section the sets with the current formats, i.e. to find out what's currently "standard" or "modern".

http://magic.wizards.com/en/content/standard-formats-magic-gathering
http://magic.wizards.com/en/gameinfo/gameplay/formats/modern

**Comment by Sembiance** [comment]
Each card in the  "extras" files has a 'legalities' field that can be used to check whether or not it's valid in the current standard and modern formats. Then it takes just a little bit of code by the user of these files to determine whether an entire set is valid in a given format or not. As far as adding another file that may list each format and which sets are valid, since this information can all be calculated pretty easily from the existing card data, I don't plan on adding such a file or fields at the set level.
