### ISSUE TITLE
[Gatherer] Fate Reforged watermark errors

### ISSUE THREAD

**Issue by Psithief** [Sembiance/mtgjson#30]
Gatherer is wrong about something. :smirk: 

FRF Abzan cards think they have the Temur watermark.
FRF Temur cards think they have no watermark.

---

I don't suppose you've ever considered sending your ever-growing list of corrections directly to rules manager [Matt](//twitter.com/tabakrules) [Tabak](http://tabakrules.tumblr.com/)?

**Comment by Sembiance** [comment]
Thanks for the heads up. Sorry for the long delay in fixing this, I was on vacation in New Zealand and just got home yesterday.  Fixed now.

As for reporting the corrections back to Matt Tabak, I wasn't aware there was an avenue of communication for gather corrections. I'm not sure I want to spend the amount of time I would need to spend in order to get gatherer corrected. There is a ton wrong.
