### ISSUE TITLE
Creatures have type "Summon" in some sets

### ISSUE THREAD

**Issue by zephyrfalcon** [Sembiance/mtgjson#35]
This isn't so important, but... a few cards in pCEL have 'types': ["Summon"]... shouldn't this be ["Creature"]? By the way, the same is true for creatures in Unglued (and one in Unhinged, "Old Fogey" :-). The 'type' attribute has the same issue.

I realize these are special sets, so maybe the usual "normalization" doesn't apply here?

**Comment by Sembiance** [comment]
I was aware of the Unglued and Unhinged cards, but I decided to keep them that way since that is the way they are on Gatherer and these are 'funky' sets.

The pCEL cards come from magiccards.info here: http://magiccards.info/uqc/en.html

These cards are not on Gatherer unfortunately, so it is not known whether or not they should be updated with the latest 'oracle' types or not. Due to these being special cards I'm hesitant to change these either, since the Unglued and Unhinged cards which are on gatherer have specifically remained the old original types which seems like a deliberate act by Wizards.

**Comment by zephyrfalcon** [comment]
I assume they won't bother to apply oracle rulings to cards that aren't legal in any format anyway... 

Still, for consistency's sake, I personally would change the 'type' and 'types' attributes (there's still the 'originalType' attribute to hold the original values). But it's your project, and your call. :) I can work around it if necessary in my project.

**Comment by Sembiance** [comment]
I've decided to make the change from Summon to Creature for the remaining cards that used Summon.

**Comment by SadisticMystic** [comment]
This should probably also apply to Denied!, which is the one Unglued card to use Interrupt as a type.

**Comment by Sembiance** [comment]
@SadisticMystic I agree. It'll get changed in the next update.
