### ISSUE TITLE
Remove 'variations' field as it is redundant

### ISSUE THREAD

**Issue by Sembiance** [Sembiance/mtgjson#64]
I am thinking about removing the 'variations' field. Essentially all it is doing is pointing to other cards in the same set that have the same name. That's it. Seems pretty easy for anyone consuming the MTGJSON data that if multiple cards in the same set have the same name, clearly they are variations of each other.

Also, right now the 'variations' field uses multiverseid's which many sets do not have, thus the field is already absent on a good number of cards and sets. So removing it would actually bring some consistency to the data.

**Comment by florentdouine** [comment]
I agree :) It's consuming too much time to fetch every urls

**Comment by flyingmutant** [comment]
Yes, sounds like a good idea.

**Comment by jenjia** [comment]
Since we still need to run trough the array of card to find the others, it doesn't make sense, as you explained. It would make more sense if the array of cards where ordered by cards number, and then the variations field would be that number. This would makes the search instant. (I know that some sets doesn't haver numbers).
(i don't know if i explained myself good, my english is so bad, god dammit)

**Comment by esb** [comment]
This change is troublesome for me. I need an array of alternatives to make it easy to match card versions. Not all systems use the same version numbering so often I have to visually verify different card versions to match things up. I need the alternatives to keep track of this process.

It was useful to know that a card had different versions as I loaded the data, so that I could build the required matching data. With that gone now, it looks like I will have to code up a second pass of the data to try to reconstruct the version data.

It would be really useful to reinstate this data as it makes my processing task a little bit easier. If people don't need the data, then it can just be ignored.

**Comment by esb** [comment]
Could I also say that it may appear to be redundant data, but the 'variations' field reports important information about a card. It says that this card has multiple versions. With the field gone, it's necessary to do additional processing on the set to determine if the card has multiple versions. This change is removing useful information about a card.

**Comment by Sembiance** [comment]
You can use the 'imageName' field as a way to determine variations. If it ends with a number, then there are variations.

One of the main problems I had with the variations array as it was is that it used multiverseid's to keep track of the variations. This being gatherer specific and gatherer missing basically every single promo card and several other sets, I didn't like that. I now have an 'id' field per card, so I could use that now in a variations field, but still feel that either using the 'imageName' field to detect variations or doing a pre-pass of the data are both acceptable.

**Comment by esb** [comment]
The image name is not a reliable field to determine the presence of variations.

For example, some of the Zendikar lands have image name ending in 'a'.

There are also instances of cards without variations having image names ending in digits. For example, the Unglued B.F.M. I also think the Deckmasters set contains a number of cards from Alliances that have variations in that set, but only 1 of the variations is included in Deckmasters but the image name still uses the variation name.

It's not really that important that cards such as promo cards don't have multiverse ids, since the variations would only apply to cards that have the same name within the one set, and the promo sets are unlikely to have any variations like this.

For me this is really a major impact on my code, and I'd rather not have to do major surgery on it just to maintain the existing function. It seems that this change is being made purely for asthetics even though it may break the code for some users. Is there a real problem with leaving it in the code, especially if it is actually being used and the alternative is to create a lot of extra work for anyone using the variations.

**Comment by Sembiance** [comment]
I will be adding the variations field back. This requires rebuilding all the sets which can take an hour or two. I'll update this issue again once the update has been deployed to the site.

**Comment by Sembiance** [comment]
Variations have been added back in.

Note: In the future I want to change the multiverseid's to hash id's. See Issue #69
